{% set name = "mapflow" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mapflow-{{ version }}.tar.gz
  sha256: b6a71a8aadbf5f9c2907b24a0ecfc9aeff3b90d87f5f06bee69f4bc598944d88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - matplotlib-base
    - geopandas
    - tqdm
    - ffmpeg

test:
  imports:
    - mapflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Python library to export xarray.DataArray as video files
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/CyrilJl/mapflow

extra:
  recipe-maintainers:
    - CyrilJl
